create table if not exists public.appointments (
    id bigint generated by default as identity primary key,
    customer_name text not null,
    customer_phone text not null,
    service text not null,
    appointment_date date not null,
    appointment_time text not null,
    created_at timestamptz not null default now(),
    constraint appointments_date_time_unique unique (appointment_date, appointment_time)
);

alter table public.appointments enable row level security;

drop policy if exists "Public can read appointments" on public.appointments;
create policy "Public can read appointments"
on public.appointments
for select
to anon
using (true);

drop policy if exists "Public can insert appointments" on public.appointments;
create policy "Public can insert appointments"
on public.appointments
for insert
to anon
with check (true);
